title: Just the Docs Template
description: A starter template for a Jeykll site using the Just the Docs theme!
theme: just-the-docs

url: https://otopalik-lab.github.io/documentation

aux_links:
  Template Repository: https://github.com/otopalik-lab/documentation
